### ISSUE TITLE
Possible Issue on First-Boot Wifi config

### ISSUE THREAD

**Issue by mjdewitt** [tanner87661/IoTTStick#14]
Hi,

First let me say that I really like what you are doing pushing the envelope on train communications. I have watched most of your videos and appreciate the level of content and thoroughness that you approach every topic. 

I was able to get IoTTStick running on an AI Thinker ESP32-cam. I ran into an issue that I believe I have run into before which is that an ESP32 will connect to the first AP that allows association, but may not be open. This fools the ESP32 into thinking it has a good connection when it doesn't. Yes, it has dhcp'd successfully, but can't pass packets.

Even if the ESP32 is successful and connects to an open AP, the question, in crowded areas, is which one? The associated AP's SSID doesn't seem to be documented/announced anywhere, or maybe I missed it?

I'm sure you can see where I'm going. With the current Wifi config hierarchy of client, AP, Client+AP, it is easy to get stuck as a client to a wrong AP.  

I believe it would be a best practice to always first-boot into AP mode and allow the user to set preferences and credentials.

I hope you find this of help.

Best,

Mike

**Comment by tanner87661** [comment]
Hi Michael

 

Thanks for your mail. Congrats to make the stick software work on a ESP32 dev board!

 

Please check the logic for the Wifi access of the Stick here: https://myiott.org/images/IoTT_Stick/Manual/IoTTStick/Unboxing_Setup/Slide10.jpg

 

If no AP is configured in the Stick, it automatically opens its own AP and when you log on, it brings you to the captive portal so you can set the AP information. If an AP is set but not available when the Stick is starting up, the same should happen. I don’t see how the stick would connect to just any AP that is around.

If no AP is configured or available, it will change to AP mode after a timeout. This is a different AP than the one with the captive portal. You can log onto it with a phone or PC just like to any other AP.

 

The problem with a devboard is that you have no screen, therefore little indication of the current mode for the stick. For this situation I have now a version on the Github that makes the onboard LED blinking depending on the connection mode. You may want to check it out, it is here: https://github.com/tanner87661/LC2021/tree/main/Sketchbook/LC2021

Check the WifiAccess.ino file and compare it to the version in the stick software to see how it works.

 

The Stick also has a button that can be used to reset the stored wifi information. This will force it to bring up the captive portal, unless it is in local AP mode. Maybe you want to add this function to your code as well. You find it from line 257 in the M5Functions.ino file. You press the button three times within a second or so and the Wifi AP settings get deleted.

 

With the Stick and the display it is by far the most convenient solution to do it the way it is right now. It’s the least efforts for the majority of users and sort of in line with what you see on other small devices with WiFi. Switch on, connect the phone, the captive portal opens automatically, enter the Wifi and set the AP information, then reboot. When it comes back it displays the IP address on screen and you can use it to connect from any PC.

 

Hope that helps.

 

Best wishes

Hans

 

From: Michael DeWitt ***@***.***> 
Sent: Monday, August 30, 2021 9:48 AM
To: tanner87661/IoTTStick ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tanner87661/IoTTStick] Possible Issue on First-Boot Wifi config (#14)

 

Hi,

First let me say that I really like what you are doing pushing the envelope on train communications. I have watched most of your videos and appreciate the level of content and thoroughness that you approach every topic.

I was able to get IoTTStick running on an AI Thinker ESP32-cam. I ran into an issue that I believe I have run into before which is that an ESP32 will connect to the first AP that allows association, but may not be open. This fools the ESP32 into thinking it has a good connection when it doesn't. Yes, it has dhcp'd successfully, but can't pass packets.

Even if the ESP32 is successful and connects to an open AP, the question, in crowded areas, is which one? The associated AP's SSID doesn't seem to be documented/announced anywhere, or maybe I missed it?

I'm sure you can see where I'm going. With the current Wifi config hierarchy of client, AP, Client+AP, it is easy to get stuck as a client to a wrong AP.

I believe it would be a best practice to always first-boot into AP mode and allow the user to set preferences and credentials.

I hope you find this of help.

Best,

Mike

**Comment by mjdewitt** [comment]
Hi Hans,

I understand what you are saying about the way networking should work, but
this was not my experience on first boot. Running your software as is out
of the box, the board was successfully dhcping to my house's main router.
Since no credentials were supplied, dhcp is as far as you get. I have found
in the past, that the esp32 wifi aggressively connect to anything it can if
no specific wifi connection info is given.

I found this in the API
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#how-to-write-a-wi-fi-application

ESP32 Wi-Fi Station Connecting When Multiple APs Are Found
<https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#esp32-wi-fi-station-connecting-when-multiple-aps-are-found>

This scenario is similar as ESP32 Wi-Fi Station Connecting Scenario
<https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#esp32-wi-fi-station-connecting-scenario>,
the difference is the station will not raise the event
WIFI_EVENT_STA_DISCONNECTED
<https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#wifi-event-sta-disconnected>
unless
it fails to connect [to any] ... of the found APs.
I believe that this is the behavior that I am running into, e.g., when no
ssid is provided a scan is performed and if there is an "Open" AP, the
esp32 connects to it.I think that this is a false positive situation that
the API doesn't seem to manage.

I have an IoTTStick on the way and so I will be able to see if there are
any differences in behavior. Just to clarify, I got the stick software up
and running on an ESP32-cam board which is like the dev kit but includes
PSRAM and a camera all for $6.

Thanks again for all of the work you have done. You have really pushed the
esp32 a long way.

Mike

**Comment by mjdewitt** [comment]
Hi,

I received my IottStick today and you are right, it behaves correctly..
Thank you very much for the enclosure that I didn't realize I needed.

I think I must have some older? library or something that is making the
difference. Based on what I see in the serial monitor, it's obvious that
they are behaving differently.

Mike
