### ISSUE TITLE
Doesn't build with latest ESP32 Core 2.0.3 

### ISSUE THREAD

**Issue by kiwi64ajs** [tanner87661/IoTTStick#28]
Hi Hans,
I just tried to build the project in the Arduino IDE using the latest ESP32 core version 2.0.3 and found it wouldn't build.

I tried version 2.0.2 and it still failed so dropped back to 1.0.6 (last of the previous major version) and the build completed - albeit with a bunch of warnings.

I wonder if it might be useful to state in the README.md file the version of the ESP32 core used for the release build so others can be confident of reproducing your set of build files

Alex

**Comment by tanner87661** [comment]
Hi Alex

Thanks for the notification. I need to look into this. I am using 1.0.6 and I assumed that was current. Normally, I always got a notification from the Arduino IDE if new versions are available. It seems this feature does no longer work for the ESP32 download repository I have in the Arduino setup. So, do I have to install it now manually?

 

Did you maybe have a look what breaks the build? A library or my code?

 

Best wishes

Hans

 

 

From: Alex Shepherd ***@***.***> 
Sent: Wednesday, June 22, 2022 5:54 PM
To: tanner87661/IoTTStick ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tanner87661/IoTTStick] Doesn't build with latest ESP32 Core 2.0.3 (Issue #28)

 

Hi Hans,
I just tried to build the project in the Arduino IDE using the latest ESP32 core version 2.0.3 and found it wouldn't build.

I tried version 2.0.2 and it still failed so dropped back to 1.0.6 (last of the previous major version) and the build completed - albeit with a bunch of warnings.

I wonder if it might be useful to state in the README.md file the version of the ESP32 core used for the release build so others can be confident of reproducing your set of build files

Alex

**Comment by atanisoft** [comment]
@tanner87661 It should still be automatic but likely you are not using the correct URL in boards manager. Refer to https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html for the updates.

Also note that Arduino-esp32 1.0.x is no longer supported so moving up is highly encouraged!

**Comment by tanner87661** [comment]
Thanks Mike, that’s timely as I wanted to look into this issue this week 😉

 

Best wishes

Hans

**Comment by tanner87661** [comment]
Problem is fixed, updated source is in the prerelease as version 1.5.14D1
Will go to master once I release the next version.
