### ISSUE TITLE
Data not loading into page

### ISSUE THREAD

**Issue by ggee** [tanner87661/IoTTStick#32]
Page are not loading properly.  Especially if you press F5.  If I refresh, I get the data loaded 1 in 10 tries.  Some timing issue maybe.

![image](https://user-images.githubusercontent.com/4544293/189029812-de6be120-618b-4d7b-89e4-07261472f690.png)

**Comment by danny117** [comment]
What did you do before this happened?

**Comment by tanner87661** [comment]
This was a timing issue depending on router and network. Scriptlist is loaded via async HTTP call while the loadInitData function runs on web socket. If the async response is delayed, scriptlist is undefined, causing this error. I added test for undefined and a delay of loadInitData if that's the case. Problem solved, will be part of the next release.
