### ISSUE TITLE
LED Chain - LED Command Sequence buttons broke if Individuals Colors

### ISSUE THREAD

**Issue by ggee** [tanner87661/IoTTStick#37]
When trying to add another "THEN THAT" action to "Individual Color" enabled LED, the + button adds blank row.

Reproduction:
1. Set multiple LED # (eg, 0,1)
2. Choose type that supports adding multiple commands (Analog Value or DCC Signal)
3. Enable "Individual Colors"
4. In "THEN THAT" column, click the + button to add another row.

This will add a blank row.  Sort of.

Further testing show that the row was added, but not shown.  If you click the + button a few more times, then toggle the "Individual Colors" box off then back on, you will see all the rows you added.

Also, if you have multiple rows (eg. 10) and click on the + at row 1, all the rows below are hidden.  Again goggle to make appear again.

Tested with 1.5.18 in Blue Hat mode.  Possibly same in other HAT modes.

![image](https://user-images.githubusercontent.com/4544293/206887781-80bcaad5-a308-49f6-9347-279796f94ea9.png)

**Comment by tanner87661** [comment]
Fixed in V. 1.5.19
