### ISSUE TITLE
LED Chain - Losing LED settings when I save and restart

### ISSUE THREAD

**Issue by ggee** [tanner87661/IoTTStick#38]
Settings in the LED chain are getting last after save and restart when 'Individual Colors' is chosen.  I enter all this data.
![image](https://user-images.githubusercontent.com/4544293/207748708-e6a22268-984e-4b9d-8982-4d495771d57d.png)

then, when I press save and restart, this is what it changes to.
![image](https://user-images.githubusercontent.com/4544293/207748803-a5f04974-6f9b-4a3a-b8d0-0472bd170ad9.png)
As seen, the UI has set them all to "Select LED 1" and many colors setting are blank.

Stranger still, when I test it with JMRI, it only wants to change LED 2 in my neopixel even though the UI only ended to with LED 1 settings.

**Comment by ggee** [comment]
For reference, I was trying to setup a double search light mast as defined on this JMRI page.
https://www.jmri.org/xml/signals/basic/appearance-two-searchlight.xml

**Comment by ggee** [comment]
[IoTTConfig.zip](https://github.com/tanner87661/IoTTStick/files/10233154/IoTTConfig.zip)
My IoTT LED config file.

[bluehat.zip](https://github.com/tanner87661/IoTTStick/files/10233235/bluehat.zip)
My JMRI panel with the one signal.

**Comment by tanner87661** [comment]
This seems to be a misunderstanding. See the attached example, using normal switch commands (3 addresses, t/c each is 6 aspects). The output is on LED's 1 and 2. 
The point is: Every aspect only has one single line. You then use the drop down selector "Select LED" to select one of the specified LED's and enter the color for that LED. Then choose the other and enter the color as well. Repeat for all aspects. That's it.

[DblSearchLight.zip](https://github.com/tanner87661/IoTTStick/files/10326828/DblSearchLight.zip)
