### ISSUE TITLE
PurpleHat doesn't seem to be assigning DCC addresses from JMRI file for speed profiling

### ISSUE THREAD

**Issue by Jay2645** [tanner87661/IoTTStick#44]
I'm trying to connect my Purplehat to a WiThrottle server, running IOTT Stick firmware version V1.5.19 (latest). However, I've noticed I'm having issues trying to run the speed profiler.

Below, you can see that Purplehat _has_ a connection to my WiThrottle server - the IOTT stick has the IP address 192.168.45.2. However, you can also see that despite having a JMRI roster entry loaded the DCC address is still "n/a". 
![image](https://user-images.githubusercontent.com/2058763/211174316-fbabb3d2-bafb-4f48-8aee-f2a3ecb7562f.png)

I can't seem to do anything to get it to respond or manually set the roster entry, either (I don't have a Loconet system to connect to).

Additionally - and maybe this is unrelated - the IOTT stick itself is not responding to the power button being held down. I can still cycle through the screens with the "main" button and I can still restart the stick from the web interface (restarting in the web UI doesn't seem to help at all, but I can see the uptime reset). It appears I'll have to wait for the battery to drain to turn the stick off and try again.

**Comment by tanner87661** [comment]
Thanks for reporting. I was able to replicate the problem, now looking into it. In the meantime, please try to install this older version 1.5.13:
https://www.dropbox.com/s/sl1auqaj70cx3qk/M5Update.zip?dl=0

See if with that version the power off button works. It might be hardware related though, sometimes, they really need a firm press.

**Comment by Jay2645** [comment]
I'm still getting the same behavior on that firmware. 🤔

I can give it a good hard squeeze and I can feel/hear the "click" of the button getting engaged, but it doesn't seem to be powering off. It doesn't seem to want to control the locomotive over WiThrottle either.
![image](https://user-images.githubusercontent.com/2058763/211180656-12c4a5b4-5938-4762-a3a2-3183078bf6f4.png)

But I'm glad you were able to reproduce! Let me know if you need anything else from me, and thanks a lot for making this. :)

**Comment by tanner87661** [comment]
Made some changes to WiThrottle Client and Server. Also fixed some other issues with data collection in Imperial mode.
Get a temporary test version here: https://www.dropbox.com/sh/e7qv4i86zeepr6i/AAACqWPWHpb0z4jN0Fhd_o5Ua?dl=0
