### ISSUE TITLE
Redhat crashes when creating a consist

### ISSUE THREAD

**Issue by ggee** [tanner87661/IoTTStick#48]
This is same content as email.  Just better here for tracking.

When using IoTT WiThrottle server, adding a second locomotive to a consist crashes the redhat.

Current setup:
Arduino Mega  DCC-EX 5.0.6
IoTT stick 1.6.4
IoTT Redhat
IoTT Power Shield
Engine Driver on Samsung S8

-  I turn on WiThrottle on the Redhat and connect with Engine Driver.
-  I select one loco from EngiveDriver and I can turn on and off the light and move the train.  
-  I now try to add a second loco in consist. 
-  Engine Driver seems ok
-  I see the screen of the M5 stick restart
-  Engine driver loses connection with the stick.

**Comment by tanner87661** [comment]
Hi Greg

 

Please check the latest version, it should work now without crashing the Stick.

Hans

 

From: ggee ***@***.***> 
Sent: Saturday, November 18, 2023 2:34 PM
To: tanner87661/IoTTStick ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tanner87661/IoTTStick] Redhat crashes when creating a consist (Issue #48)

 

This is same content as email. Just better here for tracking.

When using IoTT WiThrottle server, adding a second locomotive to a consist crashes the redhat.

Current setup:
Arduino Mega DCC-EX 5.0.6
IoTT stick 1.6.4
IoTT Redhat
IoTT Power Shield
Engine Driver on Samsung S8

*	I turn on WiThrottle on the Redhat and connect with Engine Driver.
*	I select one loco from EngiveDriver and I can turn on and off the light and move the train.
*	I now try to add a second loco in consist.
*	Engine Driver seems ok
*	I see the screen of the M5 stick restart
*	Engine driver loses connection with the stick.

**Comment by ggee** [comment]
Works in 1.6.5.
