### ISSUE TITLE
1.6.5 Save to File missing node config

### ISSUE THREAD

**Issue by ggee** [tanner87661/IoTTStick#49]
When saving to file from the Configuration tab, the json file saved does not have any of the nodes config in it.

**Comment by ggee** [comment]
and 1.6.4

**Comment by tanner87661** [comment]
Just tested it on two different Sticks. Saved files are complete and error free JSON. But it appears there might be a problem with reading back large files. Will have a closer look.

**Comment by ggee** [comment]
Interesting.  I am looking in the json file and can't find the node.cfg section.

**Comment by ggee** [comment]
My purplehat is 1.6.3 and the saved config also missing pgNodeCfg.

**Comment by ggee** [comment]
Did a little more testing.  From debugging the Arduino compile issue, I see the problem existed back in 1.6.0.

Also looking at the node, I noticed I could CTRL-click the Save button on the node screen just for the node.cfg.  That returned a file with just an empty array [ ].

**Comment by ggee** [comment]
I don't have access to latest code to do pull request.  A line was missing in WebServer.ino to get the node cfg file.

addFileToTx(client, "node", 0, "pgNodeCfg", 1); //add file



      if (thisCmd == "CfgFiles") //Config Request Format: {"Cmd":"CfgFiles", "Type":"pgxxxxCfg"}
      {
        keepAlive = millis() + keepAliveInterval;
        uint16_t fileSelector = 0xFFFF;
        if (doc.containsKey("Type"))
          fileSelector = doc["Type"];
        addFileToTx(client, "", 0, "pgStartFile", 2); //reset file list
        if (fileSelector & 0x0001)  
          addFileToTx(client, "node", 0, "pgNodeCfg", 1); //add file
        if (fileSelector & 0x0002)  
          addFileToTx(client, "mqtt", 0, "pgMQTTCfg", 1); //add file

**Comment by tanner87661** [comment]
Yes, I looked into it earlier this evening and fixed it. Thanks for finding the problem.

Hans

**Comment by tanner87661** [comment]
Hi Greg 

 

I have updated the prerelease branch with the current code 1.6.5dev

 

Hans

**Comment by ggee** [comment]
I'll try it out.   When you created the Prerelease branch, was it based off the latest master?   Just concerned since github says 

This branch is [3 commits ahead of](https://github.com/tanner87661/IoTTStick/compare/master...Prerelease), [50 commits behind](https://github.com/tanner87661/IoTTStick/compare/Prerelease...master) master.

Don't want to loose any data.

**Comment by tanner87661** [comment]
Hi Greg

The master has the latest published official release, the prerelease has any state of development. I work locally on the prerelease, then merge it to Github prerelease, and if it is an official release, I merge it into the master.

 

Hope that helps

Hans

**Comment by ggee** [comment]
Thanks for the clarification.  The save works in the prerelease branch.

**Comment by ggee** [comment]
Would you be able to tag your local commit from the original 1.6.5 and push to master?  From your latest video, sounds like it might be a while before another update.

**Comment by tanner87661** [comment]
Hi Greg

 

I refreshed the Prerelease today with the current code. I do not freeze source code as if there is a bug it will be fixed with the next release. Therefore I can’t upload a master 1.6.5, it will have to wait until I release 1.6.6 (which pretty much is what I uploaded today). 

Hans

**Comment by tanner87661** [comment]
Fixed in 1.6.6
