### ISSUE TITLE
Selecting function F10 or higher restarts redhat

### ISSUE THREAD

**Issue by ggee** [tanner87661/IoTTStick#50]
When using IoTT WiThrottle server, pressing F10 or higher restarts the IoTT stick

Current setup:
Arduino Mega DCC-EX 5.0.6
IoTT stick 1.6.5
IoTT Redhat
IoTT Power Shield
Engine Driver on Samsung S8

-    I turn on WiThrottle on the Redhat and connect with Engine Driver.
-    I select one loco from EngineDriver.
-    I can activate functions F0-F9.
-    I press F10 or higher.
-    I see the screen of the M5 stick restart
-    Engine driver loses connection with the stick.

**Comment by tanner87661** [comment]
Fixed in Version 1.6.6
